docs: change old documentation links of packages in README files
FirebaseExtended/flutterfire pull request #12136
Opened 2024-01-10 07:13 UTC by ashwinair

## Description

Changes old [firebase.flutter.dev/docs](https://firebase.flutter.dev/docs/) links to new [firebase.google.com/docs](https://firebase.google.com/docs)
of these packages:

- cloud_firestore
- cloud_firestore_web
- cloud_functions
- cloud_functions_web
- firebase_analytics
- fiebase_app_check_web
- firebase_app_installations_web
- firebase_app_installations
- firebase_core
- firebase_database
- firebase_database_web
- firebase_dynamic_links
- firebase_in_app_messaging
- firebase_messaging
- firebase_messaging_web
- firebase_ml_model_downloader
- firebase_performance
- firebase_remote_config_web
- firebase_storage
- firebase_storage_web

## Related Issues

closes #11995

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2024-01-10 13:04 UTC, russellwheatley requested changes
Hey, thanks for the PR! I've made some more suggestions to remove links to deprecated website.

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_messaging/firebase_messaging_web/README.md
>  Once installed, Cloud Messaging needs to be configured for Web Installation.  Please [see the documentation](https://firebase.flutter.dev/docs/messaging/overview#3-web-only-add-the-sdk) on Web Instal
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_database/firebase_database_web/README.md
>  available at [https://firebase.flutter.dev](https://firebase.flutter.dev)
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_database/firebase_database_web/README.md
>  Once installed, Firebase Realtime Database needs to be configured for Web Installation.  Please [see the documentation](https://firebase.flutter.dev/docs/database/overview#3-web-only-add-the-sdk) on
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_app_installations/firebase_app_installations_web/README.md
>  available at [https://firebase.flutter.dev](https://firebase.flutter.dev)
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_app_installations/firebase_app_installations_web/README.md
>  Once installed, Firebase Installations needs to be configured for Web Installation.  Please [see the documentation](https://firebase.flutter.dev/docs/installations/overview#3-web-only-add-the-sdk) on
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_app_check/firebase_app_check_web/README.md
>  available at [https://firebase.flutter.dev](https://firebase.flutter.dev)
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_app_check/firebase_app_check_web/README.md
>  Once installed, Firebase  App Check needs to be configured for Web Installation.
You can also remove this

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_analytics/firebase_analytics_web/README.md
>  available at [https://firebase.flutter.dev](https://firebase.flutter.dev)
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/firebase_analytics/firebase_analytics_web/README.md
>  Once installed, Google Analytics for Firebase needs to be configured for Web Installation.
Please remove this.

2024-01-10 13:04 UTC, russellwheatley commented on packages/cloud_functions/cloud_functions_web/README.md
>  available at [https://firebase.flutter.dev](https://firebase.flutter.dev)
```suggestion

```

2024-01-10 13:04 UTC, russellwheatley commented on packages/cloud_functions/cloud_functions_web/README.md
>  Once installed, Cloud Functions for Firebase needs to be configured for Web Installation.
Please remove this.

2024-01-10 13:04 UTC, russellwheatley commented on packages/cloud_firestore/cloud_firestore_web/README.md
```suggestion

```

2024-01-11 05:35 UTC, ashwinair commented
Hi @russellwheatley :)

I removed the lines as you suggested. can you have a look and tell me if there is anything else I have to edit.

2024-01-11 09:23 UTC, russellwheatley commented
Sorry, @ashwinair, a PR has been merged that conflicts with this file `packages/cloud_firestore_odm/cloud_firestore_odm_generator/README.md`, do you mind resolving the conflict, please? Thanks 🙏

2024-01-11 09:55 UTC, ashwinair commented
> do you mind resolving the conflict, please? Thanks 🙏

@russellwheatley, resolved.

2024-01-11 10:40 UTC, russellwheatley approved these changes

2024-01-11 11:02 UTC, exaby73 approved these changes

2024-01-11 12:21 UTC, merged