@dackers86/negative timestamp values
FirebaseExtended/flutterfire pull request #3565
Opened 2020-09-16 14:07 UTC by dackers86

Negative values would throw an error with a value less than 0. This now allows for positive and negative values within a valid range.

2020-09-17 15:50 UTC, Ehesp requested changes

2020-09-17 15:50 UTC, Ehesp commented on packages/cloud_firestore/cloud_firestore_platform_interface/test/timestamp_test.dart
> +    test('fromMillisecondsSinceEpoch can handle future date', () {
Duplicate test name here

2020-09-18 08:25 UTC, dackers86 commented on packages/cloud_firestore/cloud_firestore_platform_interface/test/timestamp_test.dart
> +    test('fromMillisecondsSinceEpoch can handle future date', () {
Thanks. Updated!

2021-01-28 13:29 UTC, mikehardy commented on packages/cloud_firestore/cloud_firestore_platform_interface/test/timestamp_test.dart
> +    test('fromMillisecondsSinceEpoch can handle nagtive millisecond values',
```suggestion
    test('fromMillisecondsSinceEpoch can handle negative millisecond values',
```

just spelling

2021-01-28 13:32 UTC, mikehardy approved these changes
LGTM - the related issue was quite informative

2021-01-28 14:15 UTC, mikehardy commented
I don't the CLA bot is about me, I have one on file and have successfully submitted PRs here :thinking:

2021-02-02 13:29 UTC, Salakar commented
@dackers86 can you double check you've signed the CLA again please, it might be due to a changed GitHub email or something.

2021-02-03 00:15 UTC, kroikie commented
@mikehardy could you try signing the CLA once more?

2021-02-03 00:33 UTC, mikehardy commented
@googlebot I fixed it.

(apparently github@mikehardy.net was not one of my alternate emails in my google organization for this user, but (weirdly!) I have successfully merged PRs here before. Go figure :-) )

2021-02-03 00:34 UTC, mikehardy commented
@kroikie CLA all set now, I'm confused how it happened but I was able to fix. Onwards!

2021-02-03 13:29 UTC, merged