fix(firebase_auth): fix firebase_auth delegate instance bug
FirebaseExtended/flutterfire pull request #3737
Opened 2020-10-01 16:29 UTC by russellwheatley

## Description

delegate getter bug. Whenever FirebaseAuth instance was retrieved, it wasn't instantiating new object. Therefore, default app and second app were the same.

Also allows constants to be set on the FirebaseAuth instance.

## Related Issues

- Fixes [#3587](https://github.com/FirebaseExtended/flutterfire/issues/3587)
- Fixes [#3604](https://github.com/FirebaseExtended/flutterfire/issues/3604)
- Fixes [#3733](https://github.com/FirebaseExtended/flutterfire/issues/3733)
## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X]  If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2020-10-02 08:31 UTC, palexs commented
Thank you, @russellwheatley! This fix is highly awaited!

2020-10-03 08:31 UTC, Ehesp requested changes

2020-10-03 08:31 UTC, Ehesp commented on packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
> +  /// Duplicate setting of [currentUser] in [_handleAuthStateChangesListener] & [_handleIdTokenChangesListener]
Double quote this one so it doesn't appear in the code docs.

2020-10-05 08:05 UTC, Ehesp approved these changes

2020-10-05 17:57 UTC, helenaford approved these changes

2020-10-05 18:08 UTC, helenaford commented
@russellwheatley approved this before I saw the `test` check failed.

2020-10-07 16:06 UTC, Ehesp approved these changes

2020-10-07 16:08 UTC, merged