test(crashlytics): update and fix
FirebaseExtended/flutterfire pull request #5187
Opened 2021-03-02 14:28 UTC by russellwheatley

## Description

This is a follow up PR for [FF-19](https://yt.invertase.io/youtrack/issue/FLUTTERFIRE-19) & [FF-20](https://yt.invertase.io/youtrack/issue/FLUTTERFIRE-20). 

Unsure if this is a breaking change as I've updated this [checkForUnsentReports()](https://github.com/FirebaseExtended/flutterfire/compare/@russell/crashlytics-follow-up-pr?expand=1#diff-ec378bc3ccbeedd0a391d573aacc9b6d96edbd7c82ab8bfc2993661151e8085aR43-R46) to throw an error if `isCrashlyticsCollectionEnabled` is set to `true`. This now matches the behaviour of RNFB Crashlytics and is the reason that test wasn't failing.

I also used the try/catch for that async test as I tried all kinds of variations of
```dart
await  expectLater(() async => await crashlytics.checkForUnsentReports(),
throwsA(isA<StateError>().having((e) => e.message, 'message',
"has been set to 'true', all reports are automatically sent")));
```
but I just couldn't get it to work. If anyone knows a better solution, I'm happy to change.

## Related Issues

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-03-05 13:41 UTC, rrousselGit commented on packages/firebase_crashlytics/firebase_crashlytics/example/test_driver/firebase_crashlytics_e2e.dart
> +          await crashlytics.checkForUnsentReports();
I don't underatand, why is the `expectLater` syntax not working?

2021-03-05 15:23 UTC, rrousselGit approved these changes

2021-03-19 14:10 UTC, Salakar requested changes
Updated the title to reflect this is actually a breaking change since it didn't throw previously.

2021-03-19 14:11 UTC, Salakar approved these changes

2021-03-19 14:12 UTC, Salakar commented
Anything blocking shipping this? cc @rrousselGit / @russellwheatley - don't want PRs to go stale if they're good to go :)

2021-03-19 15:14 UTC, russellwheatley commented
Nothing blocking from my perspective 👍

2021-03-19 15:42 UTC, rrousselGit commented
Should be good to go!

2021-03-19 15:53 UTC, merged