feat(storage, web): initial implementation of emulator
FirebaseExtended/flutterfire pull request #5936
Opened 2021-04-26 13:21 UTC by russellwheatley

## Description

Initial work for Storage emulator on the web platform.

## Related Issues

none.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-05-04 18:24 UTC, Salakar commented
Blocked pending iOS SDK 8 landing.

2021-05-14 08:29 UTC, Ehesp commented
@googlebot I consent.

2021-05-14 10:19 UTC, Salakar commented on packages/firebase_storage/firebase_storage/test/mock.dart
> +// @override
Remove?

2021-05-14 10:20 UTC, Salakar commented on packages/firebase_storage/firebase_storage_platform_interface/lib/src/platform_interface/platform_interface_firebase_storage.dart
> +  /// Set the [host] and [port] of the local emulator, such as "http://localhost"
```suggestion
  /// Set the [host] and [port] of the local emulator, such as "localhost"
```

2021-05-14 10:21 UTC, Salakar commented on packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart
> +    guard(() => webStorage!.useEmulator(host, port));
```suggestion
    guard(() => webStorage!.useEmulator(host, port));
```

It doesn't?

2021-05-14 10:25 UTC, Salakar requested changes
Minor points above

2021-05-14 15:15 UTC, Ehesp commented
Update:

- Emulator reports wrong error when a ref is not found AND not readable.
- `read` rule on emulator isn't working.
- Update metadata is throwing a dart error on web.

2021-05-16 04:52 UTC, mikehardy requested changes
mostly comments about using 9199 so the port is standard

2021-05-16 04:52 UTC, mikehardy commented on .github/workflows/scripts/firebase.json
> +      "port": "9080"
Default port for storage emulator is 9199 https://github.com/firebase/firebase-js-sdk/blob/50860d794bfe711143b5d287e1042eeb5187e47b/packages/rules-unit-testing/src/api/index.ts#L48
```suggestion
      "port": "9199"
```

2021-05-16 04:52 UTC, mikehardy commented on packages/firebase_storage/firebase_storage/example/test_driver/test_utils.dart
> +const int testEmulatorPort = 9080;
use standard / default storage emulator port

```suggestion
const int testEmulatorPort = 9199;
```

2021-05-16 04:52 UTC, mikehardy commented on packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
> +  /// Set the [host] (ex: localhost) and [port] (ex: 5001) of the local emulator.
standard storage emulator port 

```suggestion
  /// Set the [host] (ex: localhost) and [port] (ex: 9199) of the local emulator.
```

2021-05-16 04:52 UTC, mikehardy commented on packages/firebase_storage/firebase_storage_platform_interface/lib/src/full_metadata.dart
> +    print('customMetadata ${_metadata}');
debugging left over?

2021-05-16 04:52 UTC, mikehardy commented on packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
> +    print('>>>> $metadata');
debugging?

2021-05-17 09:13 UTC, Ehesp commented
Fixed the metadata issue, there was an implicit cast issue on web. Update the tests to work around emulator issues and commented out those which cannot be fixed until a fix lands on the emulator.

2021-05-17 12:04 UTC, Salakar commented on docs/storage/usage.mdx
> +If you are using the local [Storage emulators](https://firebase.google.com/docs/rules/emulator-setup), then it is possible to
```suggestion
If you are using the local [Storage emulator](https://firebase.google.com/docs/rules/emulator-setup), then it is possible to
```

2021-05-17 19:49 UTC, Salakar commented
@googlebot I consent.

2021-05-18 12:22 UTC, merged