Update macos.mdx
FirebaseExtended/flutterfire pull request #6376
Opened 2021-06-12 05:35 UTC by sultanmyrza

## Description
To be able to use firestore emulator Auth on macOS we need to allow Outgoing Connections on the Xcode's Runner.xcworkspace
here is the full [thread](https://github.com/FirebaseExtended/flutterfire/issues/6356#issue-916016860)

## Related Issues
None

## Breaking Change
None

2021-06-12 05:39 UTC, sultanmyrza commented
@googlebot I signed it!

2021-06-22 10:38 UTC, russellwheatley requested changes

2021-06-22 10:38 UTC, russellwheatley commented on docs/installation/macos.mdx
> +## Enabling use of Firebase Emulator Suit for Auth (MacOS only)
```suggestion
## Enabling use of Firebase Emulator Suit for Auth
```

2021-06-22 10:38 UTC, russellwheatley commented on docs/installation/macos.mdx
> +For mac os you need to **allow Outgoing Connections on the Xcode's Runner.xcworkspace**
```suggestion
MacOS development requires you enable `Outgoing Connections (Client)` on Xcode's Runner.xcworkspace. 
```

2021-06-22 10:38 UTC, russellwheatley commented on docs/installation/macos.mdx
> +otherwise you might get
```suggestion
Otherwise you might get the following error:
```

2021-06-22 10:38 UTC, russellwheatley commented on docs/installation/macos.mdx
> +here is the full [thread ](https://stackoverflow.com/a/66008698/6133329)
```suggestion
Here is a related StackOverflow [thread](https://stackoverflow.com/a/66008698/6133329).
```

2021-06-22 10:38 UTC, russellwheatley commented on docs/installation/macos.mdx
> +![image](https://user-images.githubusercontent.com/12681781/121333660-d1330500-c93a-11eb-8fb6-b1d803b9c7bb.png)
```suggestion
![image](https://user-images.githubusercontent.com/12681781/121333660-d1330500-c93a-11eb-8fb6-b1d803b9c7bb.png).
```

2021-08-03 12:39 UTC, russellwheatley commented
Closing in favour of: https://github.com/FirebaseExtended/flutterfire/pull/6755

2021-08-03 12:39 UTC, closed without merging