fix: App check installation doc mistake
FirebaseExtended/flutterfire pull request #6421
Opened 2021-06-19 09:04 UTC by rbrishabh

Hey @nt4f04uNd! How does this look?
Let me know if this needs any changes!
Thanks

2021-06-21 10:37 UTC, nt4f04uNd commented
Hello, I'm not a maintainer of flutterfire, so let's hope someone else, who is, will review your PR.
For reviewers, the issue this PR fixes is https://github.com/FirebaseExtended/flutterfire/issues/6413

2021-06-22 10:56 UTC, russellwheatley requested changes

2021-06-22 10:56 UTC, russellwheatley commented on docs/app-check/overview.mdx
> +### Activating the default provider
@rbrishabh, the code example is already documented [here](https://firebase.flutter.dev/docs/app-check/usage#activating-the-default-provider). Please remove. Thanks.

2021-06-23 06:49 UTC, rbrishabh commented
hi! @russellwheatley thanks for your review! done

2021-06-24 09:25 UTC, russellwheatley approved these changes

2021-06-24 09:25 UTC, merged