Fix(firebase_messaging): critical of sound causing a hidden error
FirebaseExtended/flutterfire pull request #6505
Opened 2021-06-30 03:45 UTC by guyoun

## Description

map['apple']['sound']['critical'] can be null because critical of sound is optional.
When map['apple']['sound']['critical'] is null, the TypeError raises
Because critical is non-nullable.

## Related Issues
None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-07-26 15:50 UTC, russellwheatley requested changes
minor change but LGTM.

2021-07-26 15:50 UTC, russellwheatley commented on packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
>                    volume: map['apple']['sound']['volume']));
```suggestion
                  volume: map['apple']['sound']['volume'] ?? 0,
                ),
        );
```

2021-07-28 14:37 UTC, guyoun commented on packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
>                    volume: map['apple']['sound']['volume']));
@russellwheatley Thanks.

2021-07-29 09:04 UTC, russellwheatley commented
@guyoun could you format by running `melos run format` in the root of the flutterfire directory, please? Will also need to install [melos](https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md#3-environment-setup)

2021-07-31 10:56 UTC, guyoun commented
@russellwheatley I fIxed format.

2021-08-03 08:39 UTC, russellwheatley commented
@googlebot I consent.

2021-08-03 09:54 UTC, Salakar approved these changes

2021-08-03 09:57 UTC, merged