fix(firestore, web): blob was being parsed as geopoint.
FirebaseExtended/flutterfire pull request #6728
Opened 2021-07-29 09:10 UTC by russellwheatley

## Description

The class instance received to decode for `GeoPoint` & `Blob` was the same JS object instance. Updated the if statement to check GeoPoint has the required values: `latitude` & `longitude`.

## Related Issues

fixes https://github.com/FirebaseExtended/flutterfire/issues/3865

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-08-02 11:49 UTC, lesnitsky requested changes

2021-08-02 11:49 UTC, lesnitsky commented on packages/cloud_firestore/cloud_firestore_web/lib/src/utils/decode_utility.dart
> +    return output;
```suggestion
    return data..updateAll((key, value) => valueDecode(value));
```

2021-08-02 11:49 UTC, lesnitsky commented on packages/cloud_firestore/cloud_firestore_web/lib/src/utils/decode_utility.dart
> +    return List.from(data).map(valueDecode).toList();
```suggestion
    return data.map(valueDecode).toList();
```

2021-08-02 11:49 UTC, lesnitsky commented on packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
> +      return object! as BlobJsImpl;
you can avoid bang operator with early null check return

2021-08-03 07:56 UTC, lesnitsky approved these changes
LGTM

2021-08-03 13:33 UTC, Ehesp approved these changes

2021-08-03 13:36 UTC, merged