fix(firebase_core): Fix `FirebaseException` error code bug by making default value: "unknown".
FirebaseExtended/flutterfire pull request #6897
Opened 2021-08-27 03:39 UTC by hyungtaecf

## Description

Fixing "Unhandled Exception: type 'Null' is not a subtype of type 'String'". 
Field code was receiving null from event['error']['code']. Now if it receives null it becomes the default value "unknown".

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

2021-08-31 09:40 UTC, russellwheatley commented
@hyungtaecf, could you please sign the CLA and we will look to get this fix reviewed & merged. Thanks.

2021-09-06 05:32 UTC, hyungtaecf commented
I have signed CLA right away, how can I update it here?

2021-09-07 08:28 UTC, russellwheatley commented
@hyungtaecf, simply copy: `@googlebot I signed it!`, paste it in the comment box & press `comment`.

2021-09-14 17:21 UTC, Salakar approved these changes

2021-09-17 04:10 UTC, hyungtaecf commented
@googlebot I signed it!

2021-09-29 10:18 UTC, russellwheatley requested changes
update this and we can get this merged.

2021-09-29 10:18 UTC, russellwheatley commented on packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart
> +  }), this.code = code ?? 'unknown';
```suggestion
  }): this.code = code ?? 'unknown';
```
You need to use a colon for invoking an initializer list.

2021-09-29 10:18 UTC, russellwheatley commented on packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart
> +  }), this.code = code ?? 'unknown';
@hyungtaecf

2021-10-05 08:04 UTC, russellwheatley commented
@hyungtaecf You will need to add an ignore line above your code change like this:

```dart
 FirebaseException({
    required this.plugin,
    this.message,
    String? code,
    this.stackTrace,
  // ignore: unnecessary_this
  }): this.code = code ?? 'unknown';
```

You need to install [melos tool](https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md#3-environment-setup). Run `melos run format` from root of project. Then CI will pass.

2022-01-12 12:23 UTC, merged