Update apple-integration.mdx
FirebaseExtended/flutterfire pull request #7015
Opened 2021-09-17 15:14 UTC by koltai75

## Description

- To follow to instructions the extension must be added with Objective-C language.
- Podfile target should inclide use_frameworks!
- Lines to be modified in NotificationService.m are 24-27 and not 25-28.

## Related Issues

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-09-17 15:16 UTC, koltai75 commented
@googlebot I signed it!

2021-09-22 08:50 UTC, russellwheatley requested changes
@koltai75, LGTM apart from the `use_frameworks!` directive.

2021-09-22 08:50 UTC, russellwheatley commented on docs/messaging/apple-integration.mdx
> +  use_frameworks!
remove this.

2021-09-22 09:05 UTC, koltai75 commented on docs/messaging/apple-integration.mdx
> +  use_frameworks!
Removed

2021-09-22 09:10 UTC, russellwheatley approved these changes
LGTM

2021-09-29 09:10 UTC, merged