App Check Functions Firebase Local Emulator Suite
FirebaseExtended/flutterfire pull request #7571
Opened 2021-12-12 09:10 UTC by koltai75

Added instructions how to use App Check for Functions with Firebase Local Emulator Suite.

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-01-11 16:14 UTC, russellwheatley requested changes

2022-01-11 16:14 UTC, russellwheatley commented on docs/app-check/usage.mdx
> +## App Check for Functions with Firebase Local Emulator Suite
```suggestion
## App Check for Functions
```

2022-01-11 16:14 UTC, russellwheatley commented on docs/app-check/usage.mdx
> +}
```suggestion
exports.yourCallableFunction = functions.https.onCall((data, context) => {
  // context.app will be undefined if the request doesn't include a valid
  // App Check token.
  // 
  if (context.app == undefined) {
    throw new functions.https.HttpsError(
        'failed-precondition',
        'The function must be called from an App Check verified app.')
  }

  // Your function logic follows.
});

```

2022-01-11 16:14 UTC, russellwheatley commented on docs/app-check/usage.mdx
> +The above code will not allow your functions to run in Firebase Local Emulator Suite, because App Check token won't be added when the function is called. To solve this, change the above verification
```suggestion
You may also use the [Firebase Local Emulator Suite](https://firebase.google.com/docs/emulator-suite) to test your Cloud Function. You simply have to add another conditional check (i.e. `!process.env.FUNCTIONS_EMULATOR`) to check the veracity of the caller:
```

2022-01-11 16:14 UTC, russellwheatley commented on docs/app-check/usage.mdx
> +}
```suggestion
exports.yourCallableFunction = functions.https.onCall((data, context) => {
  // context.app will be undefined if the request doesn't include a valid
  // App Check token.
  // 
  if (context.app == undefined && !process.env.FUNCTIONS_EMULATOR) {
    throw new functions.https.HttpsError(
        'failed-precondition',
        'The function must be called from an App Check verified app.')
  }
  // Your function logic follows.
});
```

2022-01-18 09:51 UTC, russellwheatley requested changes
A couple of nitpicks, but LGTM once changes made. Thanks.

2022-01-18 09:51 UTC, russellwheatley commented on docs/app-check/usage.mdx
> +  //
```suggestion
 
```

2022-01-18 09:51 UTC, russellwheatley commented on docs/app-check/usage.mdx
> +  //
```suggestion
 
```

2022-01-18 11:04 UTC, russellwheatley requested changes
Sorry, just noticed one other change to make 😅

2022-01-18 11:04 UTC, russellwheatley commented on docs/app-check/usage.mdx
> +You may also use the [Firebase Local Emulator Suite](https://firebase.google.com/docs/emulator-suite) to test your Cloud Function. You simply have to add another conditional check (i.e. `!process.env
```suggestion
You may also use the [Firebase Local Emulator Suite](https://firebase.google.com/docs/emulator-suite) to test your Cloud Function. You simply have to add another conditional check (i.e. `!process.env.FUNCTIONS_EMULATOR`) to stop errors from throwing whilst testing:
```

2022-01-18 11:05 UTC, koltai75 commented on docs/app-check/usage.mdx
> +You may also use the [Firebase Local Emulator Suite](https://firebase.google.com/docs/emulator-suite) to test your Cloud Function. You simply have to add another conditional check (i.e. `!process.env
No problem!

2022-01-18 11:40 UTC, merged