added bahasa (indonesia) languange
FirebaseExtended/flutterfire pull request #7709
Opened 2021-12-27 00:57 UTC by ekasetiawans

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-01-13 14:24 UTC, lesnitsky commented on packages/flutterfire_ui/lib/src/i10n/default_localizations.dart
> +import 'package:flutterfire_ui/src/i10n/lang/id.dart';
```suggestion
import 'lang/id.dart';
```

2022-01-13 14:26 UTC, lesnitsky commented on packages/flutterfire_ui/lib/src/i10n/lang/id.dart
> +    this.arrayLabel = 'array',
@ekasetiawans would you be able to translate this as well as the labels below?

2022-01-13 14:26 UTC, lesnitsky requested changes
DataTable labels require translations

2022-01-13 22:47 UTC, ekasetiawans commented
@lesnitsky i did it

2022-01-27 16:36 UTC, ekasetiawans reviewed
thanks

2022-02-07 10:57 UTC, ekasetiawans reviewed
okay

2022-02-15 12:05 UTC, russellwheatley commented
Hey @ekasetiawans, thanks for the PR! I don't suppose you are able to have your Bahasa Indonesia double checked by someone who speaks the language (i.e get this PR approved by a developer who speaks the language)? Just for spellchecking and correct language interpretation. Sadly, I don't know anyone from Indonesia 😄

2022-02-15 12:15 UTC, ekasetiawans commented
@russellwheatley do you mean anyone from Indonesia or just for collaboratos from Indonesia?

2022-02-15 12:22 UTC, russellwheatley commented
@ekasetiawans, someone you know would be fine. I prefer a proofreading whenever there's a labelling/documentation PR.

2022-02-15 12:44 UTC, ekasetiawans commented
@russellwheatley I'm very new to open source collaboration, so I need some guidance in case something goes wrong.

2022-02-15 13:41 UTC, RTheTopanX404 commented
@ekasetiawans  ..
I'm already check all of translations to Indonesia, and everything is translated to Indonesia .

2022-02-15 14:54 UTC, merged