fix(firebase_analytics): example app initialization and docs support status
FirebaseExtended/flutterfire pull request #7745
Opened 2021-12-31 15:22 UTC by pr-Mais

## Description

Fixed the initialization part in the example app for firebase_analytics and addd the support status section to show which plugins/platforms currently doesn't support the Dart-only initialization.

## Related Issues

Possibly related issues #7639 #7543 #7520

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-01-04 10:24 UTC, russellwheatley requested changes
A few small changes from me. I think you'll also need to add back in the google service file for example/android as well.

2022-01-04 10:24 UTC, russellwheatley commented on docs/auth/social.mdx
> +Dart-only initialization isn't yet support by `google_sign_in` plugin, in which case you still have to do the [manual installation](./manual-installation.mdx) if you're using Google as an auth provid
```suggestion
Dart-only initialization isn't yet supported by `google_sign_in` plugin, in which case you still have to do the [manual installation](./manual-installation.mdx) if you're using Google as an auth provider.
```

2022-01-04 10:24 UTC, russellwheatley commented on docs/cli.mdx
> +Some plugins or platforms doesn't support Dart-only initialization **yet**, for which you will use the platform
```suggestion
Some plugins or platforms do not support Dart-only initialization **yet**, for which you will use the platform
```

2022-01-04 10:24 UTC, russellwheatley commented on docs/cli.mdx
> +config files through the [manual installation](./manual-installation.mdx), the following table shows the current
```suggestion
config files through the [manual installation](./manual-installation.mdx). The following table shows the current
```

2022-01-04 13:11 UTC, Ehesp commented
Is the PR title correct here? It says fix but only applies docs and examples changes so shouldn't change versions of anything?

2022-01-04 13:11 UTC, pr-Mais commented
yes I agree, `docs` could be?

2022-01-05 13:22 UTC, Salakar commented on docs/auth/social.mdx
> +Dart-only initialization isn't yet supported by `google_sign_in` plugin, in which case you still have to do the [manual installation](./manual-installation.mdx) if you're using Google as an auth prov
```suggestion
Dart-only Firebase initialization isn't yet supported by `google_sign_in` plugin, if you're using Google as an auth provider you'll still have to do the [manual installation](./manual-installation.mdx) steps to integrate the Firebase configuration files.
```

2022-01-05 13:23 UTC, merged