[📚] Add what "ODM" stands for #7780
FirebaseExtended/flutterfire pull request #7791
Opened 2022-01-05 14:16 UTC by KikiManjaro

## Description

First contribution ever
[📚] Add what "ODM" stands for #7780
Add a paragraph for what ODM stands for in [here](https://firebase.flutter.dev/docs/firestore-odm/overview/)

## Related Issues

https://github.com/FirebaseExtended/flutterfire/issues/7780

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-01-06 08:57 UTC, rrousselGit commented on docs/firestore-odm/overview.mdx
> +The Object Document Model or ODM is an interface that treats a document as a tree structure wherein each node is an object representing a part of the document. .
```suggestion
The Object Document Mapper or ODM is an interface that treats a document as a tree structure wherein each node is an object representing a part of the document.   
```

2022-01-09 13:15 UTC, KikiManjaro commented
I don't understand why the task `website / preview (pull_request) Failing after 1m` is failling. Does someone have an idea ?

2022-02-10 11:22 UTC, russellwheatley requested changes
Small tweaks.

2022-02-10 11:22 UTC, russellwheatley commented on docs/firestore-odm/overview.mdx
> +ODM methods allow programmatic access to the tree; with them one can change the structure, style or content of a document.
```suggestion
ODM methods allow programmatic access to the tree making it possible to change the structure, style or content of a document. 
```

2022-02-10 11:22 UTC, russellwheatley commented on docs/firestore-odm/overview.mdx
> +## What is an ODM ?
```suggestion
## What is an ODM?
```

2022-02-10 11:24 UTC, russellwheatley commented on docs/firestore-odm/overview.mdx
> +## What is an ODM ?
@KikiManjaro thanks for the PR, some small tweaks 😄

2022-02-15 10:03 UTC, rrousselGit commented
I think this is good to go. Let's merge it

2022-02-15 10:04 UTC, merged