feat(flutterfire_ui): added French language
FirebaseExtended/flutterfire pull request #7797
Opened 2022-01-05 18:43 UTC by KikiManjaro

## Description

Added localizations for the French language.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-01-05 22:08 UTC, malbolged requested changes
@KikiManjaro Please fix these.
Thanks :)

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +        'Utiliseez une des méthodes suivantes pour vous connecter',
Utilisez une des méthodes suivantes pour vous connecter

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.booleanLabel = 'boolean',
booléen

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.numberLabel = 'number',
numéro

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.stringLabel = 'string',
chaîne de caractères

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.valueLabel = 'value',
valeur

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.cancelLabel = 'cancel',
annuler

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.updateLabel = 'update',
mettre à jour

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.westInitialLabel = 'W',
O

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.referenceLabel = 'reference',
référence

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.timestampLabel = 'timestamp',
horodatage

2022-01-05 22:08 UTC, malbolged commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.geopointLabel = 'geopoint',
géopoint

2022-01-05 22:25 UTC, KikiManjaro commented
Done ! :) Was not sure if the last ones should be translate, my bad

2022-01-05 22:55 UTC, malbolged approved these changes

2022-01-06 10:36 UTC, rrousselGit commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.verifyCodeButtonText = 'Verifier',
```suggestion
    this.verifyCodeButtonText = 'Vérifier',
```

2022-01-06 10:37 UTC, rrousselGit commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +    this.verifyingSMSCodeText = 'Verification du code SMS',
```suggestion
    this.verifyingSMSCodeText = 'Vérification du code SMS',
```

2022-01-06 10:38 UTC, rrousselGit commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +        "Nous vous avons envoyé un email avec un lien pour réinitialiser votre mot de passe. Veuillez verifier vos emails.",
```suggestion
        "Nous vous avons envoyé un email avec un lien pour réinitialiser votre mot de passe. Veuillez vérifier vos emails.",
```

2022-01-06 10:39 UTC, rrousselGit commented on packages/flutterfire_ui/lib/src/i10n/lang/fr.dart
> +        "Nous vous avons envoyé un email avec un lien magique. Verifiez vos emails et clickez sur le lien pour vous connecter",
```suggestion
        "Nous vous avons envoyé un email avec un lien magique. Vérifiez vos emails et clickez sur le lien pour vous connecter",
```

2022-01-06 10:40 UTC, rrousselGit approved these changes
LGTM

2022-01-06 10:42 UTC, Salakar approved these changes

2022-01-06 10:42 UTC, merged