Update overview.mdx
FirebaseExtended/flutterfire pull request #7926
Opened 2022-01-22 16:16 UTC by kagouda

To solve this problem: 
https://github.com/FirebaseExtended/flutterfire/issues/7805
And I added the difference between FlutterFire CLI and Firebase CLI, because it's not the same thing.  Also the FlutterFire CLI depends on the Firebase CLI so it must be installed before you can use it

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-01-25 10:01 UTC, russellwheatley requested changes
A few nits. Thanks.

2022-01-25 10:01 UTC, russellwheatley commented on docs/overview.mdx
> +If not, make sure you have [node.js](https://www.nodejs.org/) on your machine and Install the Firebase CLI via npm by running the following command :
```suggestion
You will also need [node.js](https://www.nodejs.org/) on your machine to Install the Firebase CLI via npm by running the following command: 
```

2022-01-25 10:26 UTC, kagouda commented
Thanks you @russellwheatley

2022-01-25 10:49 UTC, Salakar commented
Could these changes be perhaps moved to /cli docs page instead?

2022-01-25 11:44 UTC, russellwheatley commented
@kagouda, As @Salakar suggested, could you move these changes to the CLI page here: https://firebase.flutter.dev/docs/cli, please? Thanks 😄.

2022-01-28 11:55 UTC, kagouda commented
@Salakar  it think it's ok now

2022-02-01 10:16 UTC, russellwheatley requested changes
As long as @Salakar is happy with the link from `docs/overview.mdx`, and the tweaks I've requested, it LGTM.

2022-02-01 10:16 UTC, russellwheatley commented on docs/overview.mdx
>  ### Using the CLI
```suggestion
### Using the FlutterFire CLI
```

2022-02-01 10:16 UTC, russellwheatley commented on docs/overview.mdx
> +:::info The FlutterFire CLI depends on the [Firebase CLI](https://firebase.google.com/docs/cli).  If you haven't installed it yet, you can learn more about Firebase CLI in the [documentation](https:/
```suggestion
:::info 

The FlutterFire CLI depends on the [Firebase CLI](https://firebase.google.com/docs/cli).  If you haven't installed it yet, you can learn more about Firebase CLI in the [documentation](https://firebase.google.com/docs/cli). 

:::
```

2022-02-08 11:44 UTC, russellwheatley commented
Hey @kagouda, we're happy with the changes, but could you make necessary updates so that the `website / validate` CI check passes? In a nutshell, change "behaviour" to "behavior" (US spelling) & add "npm" to the [dictionary](https://github.com/FirebaseExtended/flutterfire/blob/master/website/dictionary.js) file. Thanks.

2022-02-08 16:18 UTC, kagouda commented
Hi @russellwheatley   . I have updated the dictionary and other . So I think it's OK. But where is the "behavior" that I should change "behavior" ?

2022-02-08 17:03 UTC, russellwheatley commented
@kagouda, here is the CI test that is failing https://github.com/FirebaseExtended/flutterfire/runs/5112709183?check_suite_focus=true

You need to add "npm" to dictionary, not "node".  Thanks.

2022-02-08 17:56 UTC, kagouda commented
@russellwheatley I've already updated the dictionary.

2022-02-09 14:48 UTC, merged