add optional initialData [SignInScreen]
FirebaseExtended/flutterfire pull request #8036
Opened 2022-02-08 02:05 UTC by rubensdemelo

add `initialData: FirebaseAuth.instance.currentUser` in  SignInScreen to avoid get `null`  in authStateChanges() even with user is signed in.

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-02-08 10:07 UTC, russellwheatley requested changes
Thanks @rubensdemelo for the PR, I've tweaked a little bit.

2022-02-08 10:07 UTC, russellwheatley commented on docs/ui/auth/integrating-your-first-screen.mdx
> +  //optional
```suggestion
  // If the user is already signed-in, use it as initial data
```

2022-02-08 10:07 UTC, russellwheatley commented on docs/ui/auth/integrating-your-first-screen.mdx
> +
```suggestion
```

2022-02-08 12:21 UTC, rubensdemelo commented
> Thanks @rubensdemelo for the PR, I've tweaked a little bit.

Should I make any change ?

2022-02-09 11:12 UTC, rubensdemelo commented
Not sure about that statement, because even user isnt signin, `initialData: FirebaseAuth.instance.currentUser` will return `false`. 

And on first build, authStateChanges returns `null`.

2022-02-09 14:49 UTC, rubensdemelo commented
> Hey @rubensdemelo, not sure what you mean? [See here](https://github.com/FirebaseExtended/flutterfire/blob/aff72a20ce01ccb855442373b9f005dacb6f8a45/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart#L61).
> 
> Also - the example uses a condition where it won't matter if it is `null` or `false`:
> 
> ```dart
>   if (!snapshot.hasData) {
>       return SignInScreen(
>         providerConfigs: []
>       );
>     }
> ```

Thanks

2022-02-10 10:38 UTC, merged