Fix type cast issue with utmParameters
FirebaseExtended/flutterfire pull request #8263
Opened 2022-03-11 19:47 UTC by odlund

## Description

The `PendingDynamicLinkData` constructs expects the parameter `utmParams` to be a `Map<String, String>` but was passed a `Map<dynamic,dynamic>` this silently fails with a typecast exception and deep links seems to just not show up in the flutter app.

## Related Issues

#8261 #7697 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-03-12 23:01 UTC, nilsreichardt commented
@russellwheatley It seems so that the current version (`4.10.0`) of `firebase_dynamic_links` doesn't work. I'm not able to receive dynamic links with `onLink`. I haven't tested it yet, but other users complaining that `getInitialLink` also not working (see https://github.com/FirebaseExtended/flutterfire/issues/8261).

With the PR of @odlund, it's working again.

It would be nice to have (integration) tests which catch these kinds of issues. Otherwise, almost the entire packing isn't working anymore.

2022-03-12 23:01 UTC, nilsreichardt commented
@russellwheatley It seems so that the current version (`4.10.0`) of `firebase_dynamic_links` doesn't work. I'm not able to receive dynamic links with `onLink`. I haven't tested it yet, but other users complaining that `getInitialLink` also not working (see https://github.com/FirebaseExtended/flutterfire/issues/8261).

With the PR of @odlund, it's working again.

It would be nice to have (integration) tests which catch these kinds of issues. Otherwise, almost the entire packing isn't working anymore.

2022-03-14 00:36 UTC, crushman1 commented
this issue is happening on `firebase_dynamic_links: ^4.0.7` as well. it says `type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, String>'` when it gets data in not null in `final PendingDynamicLinkData? data = await FirebaseDynamicLinks.instance.getInitialLink();`

2022-03-14 06:25 UTC, scott-the-brewer commented
I can confirm this works for me. Thanks @odlund

2022-03-15 12:07 UTC, russellwheatley requested changes
Thank you for the PR 🙏.

2022-03-15 12:07 UTC, russellwheatley commented on packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/method_channel/method_channel_firebase_dynamic_links.dart
> +      utmParameters: Map<String,String>.from(linkData['utmParameters']),
```suggestion
linkData['utmParameters'] == null
          ? {}
          : Map<String, String>.from(linkData['utmParameters'])
```

2022-03-15 12:27 UTC, russellwheatley commented
@odlund Thank you for PR, but I've opened a new one [here](https://github.com/FirebaseExtended/flutterfire/pull/8280/files) given it needs to be merged and released ASAP. I tried to push to your repo but no write permission apparently. Thanks again!

2022-03-15 12:27 UTC, closed without merging