docs: point to "firebase.google" domain for hyperlinks in the usage section of `README.md` files (for the missing packages)
FirebaseExtended/flutterfire pull request #8818
Opened 2022-06-01 14:38 UTC by nilsreichardt

## Description

https://github.com/firebase/flutterfire/pull/8814 was a draft pull request because it was just a proposal for a few packages 🙈

> This PR is a proposal and should show a proof of concept for the new format. If this is a good solution, I will continue adding the links for the other packages.

This PR adds the links for the other packages.

cc: @russellwheatley 

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2022-06-07 07:41 UTC, russellwheatley requested changes
Thanks, @nilsreichardt. A few updates and it LGTM.

2022-06-07 07:41 UTC, russellwheatley commented on packages/firebase_analytics/firebase_analytics/README.md
> +To use this plugin, please visit the [Analytics Usage documentation](https://firebase.google.com/docs/firestore/quickstart#add_data)
```suggestion
To use this plugin, please visit the [Analytics Usage documentation](https://firebase.google.com/docs/analytics/events?platform=flutter)
```

2022-06-07 07:41 UTC, russellwheatley commented on packages/cloud_functions/cloud_functions/README.md
> +To use this plugin, please visit the [Functions Usage documentation](https://firebase.google.com/docs/functions/callable#call_the_function)
```suggestion
To use this plugin, please visit the [Functions Usage documentation](https://firebase.google.com/docs/functions/callable#dart)
```

2022-06-07 09:54 UTC, nilsreichardt commented on packages/firebase_analytics/firebase_analytics/README.md
> +To use this plugin, please visit the [Analytics Usage documentation](https://firebase.google.com/docs/firestore/quickstart#add_data)
omg, thanks

2022-06-07 10:18 UTC, russellwheatley approved these changes

2022-06-16 09:12 UTC, Lyokone approved these changes

2022-06-16 09:12 UTC, merged